<?php

class ConnectionEventListenerTest extends TestCase
{
    use \Illuminate\Foundation\Testing\DatabaseMigrations;
    /**
     * @var instance of \Sawfly\Visitors\Events\ConnectionEvent
     */
    private $ce;
    /**
     * @var instance of \Sawfly\Visitors\Listeners\ConnectionEventListener
     */
    private $cel;
    /**
     * @var \Carbon\Carbon::today()->format('Y-m-d')
     */
    private $today;

    /**
     * Starting sets
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->today = \Carbon\Carbon::today()->format('Y-m-d');
        $request = new \Illuminate\Http\Request();
        $this->ce = new \Sawfly\Visitors\Events\ConnectionEvent($request);
        $this->cel = new \Sawfly\Visitors\Listeners\ConnectionEventListener();
    }

    /**
     * test handle()
     */
    public function testHandle()
    {
        $this->assertInstanceOf(\Sawfly\Visitors\Listeners\ConnectionEventListener::class, $this->cel);
        $this->cel->handle($this->ce);
        $this->seeInDatabase('visitors', ['created_at' => $this->today]);
    }
}