<?php

class ConnectionEventTest extends TestCase
{
    /**
     * @var instance of \Sawfly\Visitors\Events\ConnectionEvent
     */
    private $ce;

    /**
     * Starting sets
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $request = new \Illuminate\Http\Request();
        $this->ce = new \Sawfly\Visitors\Events\ConnectionEvent($request);
    }

    /**
     * test getRequest()
     */
    public function testGetRequest()
    {
        $this->assertInstanceOf(\Sawfly\Visitors\Events\ConnectionEvent::class, $this->ce);
        $this->assertInstanceOf(\Illuminate\Http\Request::class, $this->ce->getRequest());
    }
}